### ISSUE TITLE
Do we need to know the transform between different patterns?

### ISSUE THREAD

**Issue by zhaozhongch** [oliver-batchelor/multical#19]
Thanks for the work. The question is as the title. 
Another following up is if one camera needs to visualize all the patterns? Can one camera just visualize one pattern or even part of one pattern for calibration?

**Comment by oliver-batchelor** [comment]
Currently it will only work if there is overlap between patterns (in at
least some of the views). It will calibrate the transform between those
patterns.

There is a method to initialise the calibration for non-overlapping
patterns (e.g. two cameras viewing different patterns facing in opposite
directions), it's just that I haven't implemented it. The key is to use a
hand-eye calibration procedure on the estimated board poses. I've even
wrapped the OpenCV code for this - just haven't done the code for the
initialisation!

Cheers,
Oliver

**Comment by zhaozhongch** [comment]
Thanks for the fast reply. Another question is do we need to know the relative position between the patterns for the calibration? If so, it might be none-trivial to obtain a high precision relative position between different patterns.
