### ISSUE TITLE
360 rig calibration

### ISSUE THREAD

**Issue by vswdigitall** [oliver-batchelor/multical#33]
Hi, example shows all cameras sees all boards at same time.

Will it work for 360rig setup? 
Cameras has 10% overlap.

![photo1659817100](https://user-images.githubusercontent.com/48950231/183266734-386fcc7b-8948-49f2-816c-369199b76246.jpeg)

**Comment by oliver-batchelor** [comment]
Hmm. It might work but I think to be robust it would need a different kind of initialisation which uses a so called "hand-eye" calibration. I have not done this yet but it is very do-able!

This enables good starting estimates for cameras with no overlap at all!

**Comment by demul** [comment]
@oliver-batchelor
Thanks Oliver. Can u explain more about the reason why it world need a different kind of initialization?
If there is 10% overlap, Initial extrinsics between cameras would be not precise?
