### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by slovak194** [oliver-batchelor/multical#50]
Hi!

Does not work with newer Numpy.

`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int
32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:  
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The error appears here:
https://github.com/oliver-batchelor/multical/blob/af1fddaab43d8622c043a5d2eef56cbe74e48299/multical/board/common.py#LL16C1-L17C1

Best regards,
Alex

**Comment by oliver-batchelor** [comment]
Fixed by #51
