### ISSUE TITLE
No module named 'apriltags_eth'

### ISSUE THREAD

**Issue by Sadra1999** [oliver-batchelor/multical#62]
Hi 

After pip install multical, the module 'apriltags_eth' still cannot be found. Searching 'apriltags_eth' online gives nothing suitable. Please refer to multical/board/aprtilgrid_detector.py  Line 1 for more details. 

Looking forward to your reply, thank you!

**Comment by chenzhekl** [comment]
Hi @Sadra1999 , I am facing the same issue. How did you manage to solve it?

**Comment by jongwook-bae** [comment]
@Sadra1999 @chenzhekl 

check this issue, it will solve the problem.

https://github.com/oliver-batchelor/multical/issues/20#issuecomment-1033242533
