### ISSUE TITLE
How to write the calibration command

### ISSUE THREAD

**Issue by Mabroukiimen** [oliver-batchelor/multical#63]
I am trying to perform calibration on 8 cameras and this is the way I write the command: multical calibrate --cameras C11139,C11140,C11141,C11458,C11459,C11461,C11462,C11463
with : C11139,C11140,C11141,C11458,C11459,C11461,C11462,C11463 are the name of my 8 cameras but it gives me this error: ValueError: mutable default <class 'multical.config.arguments.PathOpts'> for field paths is not allowed: use default_factory
Can someone please confirm how to write the command (what's to replace and what's not ? )

Thank you in advance!!

**Comment by oliver-batchelor** [comment]
Hi,

This is an error which python 3.11 started producing. It’s from the
dataclass, they no longer allow default values of mutable types. The usual
answer is to make the field immutable (if it is a dataclass adding
frozen=True)

**Comment by Mabroukiimen** [comment]
Hello, I understand, thank you so much for the quick response and the excellent work!
